### ISSUE TITLE
Why does "NUM_BUCKETS = NUM_PES"?

### ISSUE THREAD

**Issue by Zhiming-Wang** [ParRes/ISx#1]
I think normal distributions (or Gaussian) are used in the natural and social sciences to represent real-valued random variables. At source version, the number of keys of each rank is tried to keep roughly equal.
/\*  Determine Redistibution of keys: accumulate the bucket size totals
    till this number surpasses NUM_KEYS (which the average number of keys
    per processor).  Then all keys in these buckets go to processor 0.
    Continue accumulating again until supassing 2*NUM_KEYS. All keys
    in these buckets go to processor 1, etc. 
    ......
*/
If "NUM_BUCKETS = NUM_PES", I think the amount of computation will be unbalance. Why did you do that? Can you describe the reason for doing this.
I'm curious and want to learn from you. Thanks very much.

**Comment by jrhemstad** [comment]
You are correct that the data distribution from NAS IS is a semi-normal distribution and therefore they use a number of buckets greater than the number of PEs in order to attempt load balancing. However, their method of load balancing (as you described) ends up with greatly imbalanced keys per bucket, and is therefore not effective.

On the other hand, for ISx, we chose to use a uniform random data distribution. Thus, we do not need to do any load balancing and we can safely set NUM_BUCKETS = NUM_PES because the key distribution is already perfectly load balanced.

That said, in future versions of ISx I would like to add an option to specify different data distributions and implement a load balancing scheme to handle non-uniformly distributed keys.

Feel free to keep asking questions!
