### ISSUE TITLE
Unsorted keys in PE's bucket

### ISSUE THREAD

**Issue by Ashutosh-Londhe** [ParRes/ISx#19]
In the NPB Integer sort key's are not only in range of PE's bucket boundary but also they are in sorted order within the bucket. If the ISx is inspired by NPB Integer sort, then why it just implementing sending of the keys to respective PE's bucket and NOT doing actual sorting of those keys within the bucket. Or is the ISx just implemented to understand the all-to-all communication pattern of bucket sort algorithm.

**Comment by jdinan** [comment]
Thanks for your note. The focus of ISx has indeed been on the communication pattern and its scalability. I'm not familiar enough with the original NAS benchmark to draw a comparison, but there is a routine `count_local_keys` in ISx that inserts the keys received during the `exchange_keys` phase into the local table. Because of the data structures used, this can be done in `O(N)` regardless of whether the keys received are in sorted order.

**Comment by Ashutosh-Londhe** [comment]
Hello James,

Thanks for the clarification and also for providing the guidelines for sorting implementation.

**Comment by jdinan** [comment]
Looks like there is nothing more to address here. Please re-open this issue, if needed.

**Comment by jrhemstad** [comment]
Apologies I didn't notice this issue in my notifications until it was closed.

>there is a routine count_local_keys in ISx that inserts the keys received during the exchange_keys phase into the local table. Because of the data structures used, this can be done in O(N) regardless of whether the keys received are in sorted order.

It's been a while, but from what I remember, this is correct. The last step is basically to compute a histogram of the keys on each PE (counting sort). Materializing the keys in sorted order is just a matter of iterating the histogram and copying `histogram[i]` elements of key `i` into the final sorted list. Seeing as though that's an uninteresting operation it wasn't deemed important to do.
